"use client"

import { useState, useEffect } from "react"
import { Eye, FileText, CheckCircle2, XCircle, RefreshCw, History } from "lucide-react"
import { createClient } from "@/lib/supabase/client"
import Link from "next/link"
import { updateQuoteStatus } from "@/app/actions/quote"
import { toast } from "sonner"
import { useLanguage } from "@/components/language-provider"
import { ActivityLogsModal } from "@/components/logs/ActivityLogsModal"

export default function ProposalsPage() {
  const [proposals, setProposals] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [userProfile, setUserProfile] = useState<any>(null)
  const [logsQuote, setLogsQuote] = useState<any>(null)
  const [currentPage, setCurrentPage] = useState(1)
  const [itemsPerPage, setItemsPerPage] = useState(10)
  const [sortConfig, setSortConfig] = useState({ key: 'created_at', direction: 'desc' })
  
  const supabase = createClient()
  const langContext = useLanguage()
  const lang = (langContext === 'en' || langContext === 'es') ? langContext : 'es'

  const t = {
    es: {
      title: 'Propuestas Listas',
      subtitle: 'Propuestas generadas por Underwriting listas para ser presentadas a tu cliente.',
      loading: 'Loading proposals...',
      empty: 'Aún no tienes propuestas generadas.',
      updating: 'Actualizando estado...',
      updateSuccess: 'Estado actualizado correctamente',
      updateError: 'Error al actualizar',
      client: 'Cliente',
      business: 'Negocio',
      lineOfBusiness: 'Línea de Negocio',
      coverages: 'Coberturas',
      totalPremium: 'Prima Total',
      estimatedPremium: 'Prima Estimada',
      status: 'Estado',
      action: 'Acción',
      viewPresentation: 'Ver Presentación',
      statuses: {
        QUOTED: 'Pendiente Presentar',
        PROCESSING: 'Cambiar / Revisar',
        ACCEPTED: 'Aceptada',
        REJECTED: 'Rechazada'
      }
    },
    en: {
      title: 'Ready Proposals',
      subtitle: 'Proposals generated by Underwriting ready to be presented to your client.',
      loading: 'Loading proposals...',
      empty: 'You do not have any generated proposals yet.',
      updating: 'Updating status...',
      updateSuccess: 'Status updated successfully',
      updateError: 'Error updating',
      client: 'Client',
      business: 'Business',
      lineOfBusiness: 'Line of Business',
      coverages: 'Coverages',
      totalPremium: 'Total Premium',
      estimatedPremium: 'Estimated Premium',
      status: 'Status',
      action: 'Action',
      viewPresentation: 'View Presentation',
      statuses: {
        QUOTED: 'Pending Presentation',
        PROCESSING: 'Change / Review',
        ACCEPTED: 'Accepted',
        REJECTED: 'Rejected'
      }
    }
  }[lang]

  const loadData = async () => {
    setLoading(true)
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return

    const { data: profile } = await supabase
      .from("profiles")
      .select("*")
      .eq("id", user.id)
      .single()
      
    setUserProfile(profile)

    // Solo traemos las solicitudes que ya fueron cotizadas o posterior
    let query = supabase
      .from("quote_requests")
      .select(`*, profiles!agent_id(name, agency_id), assignee:profiles!assigned_to(name), agencies(name, logo_url)`)
      .in('status', ['QUOTED', 'ACCEPTED', 'REJECTED'])
      .order("created_at", { ascending: false })
      
    // Si no es admin/manager, solo ve las suyas
    if (profile && profile.role === 'AGENT') {
        query = query.or(`agent_id.eq.${user.id},assigned_to.eq.${user.id}`)
    } else if (profile && profile.role === 'MANAGER') {
        query = query.eq('agency_id', profile.agency_id)
    }
    
    const { data } = await query
    
    if (data) setProposals(data)
    setLoading(false)
  }

  const handleStatusChange = async (quoteId: string, newStatus: string) => {
    const prevProposals = [...proposals]
    setProposals(proposals.map(p => p.id === quoteId ? { ...p, status: newStatus } : p))
    
    const toastId = toast.loading(t.updating)
    try {
      const res = await updateQuoteStatus(quoteId, newStatus)
      if (res.success) {
        toast.success(t.updateSuccess, { id: toastId })
      } else {
        throw new Error(res.error || t.updateError)
      }
    } catch (e: any) {
      toast.error(e.message, { id: toastId })
      setProposals(prevProposals)
    }
  }

  useEffect(() => {
    loadData()
  }, [])

  const sortedProposals = [...proposals].sort((a, b) => {
    let aValue = a[sortConfig.key]
    let bValue = b[sortConfig.key]
    
    if (sortConfig.key === 'client_name') {
      aValue = a.client_name || ''
      bValue = b.client_name || ''
    } else if (sortConfig.key === 'quoted_premium') {
      aValue = a.quotes_provided?.[0]?.total_premium || 0
      bValue = b.quotes_provided?.[0]?.total_premium || 0
    } else if (sortConfig.key === 'carrier_commission') {
      aValue = a.quotes_provided?.[0]?.agency_commission_percentage || 0
      bValue = b.quotes_provided?.[0]?.agency_commission_percentage || 0
    } else if (sortConfig.key === 'status') {
      aValue = a.status || ''
      bValue = b.status || ''
    } else if (sortConfig.key === 'created_at') {
      aValue = new Date(a.created_at).getTime()
      bValue = new Date(b.created_at).getTime()
    }

    if (aValue < bValue) return sortConfig.direction === 'asc' ? -1 : 1
    if (aValue > bValue) return sortConfig.direction === 'asc' ? 1 : -1
    return 0
  })

  const totalPages = Math.ceil(sortedProposals.length / itemsPerPage)
  const paginatedProposals = sortedProposals.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage)

  return (
    <div className="flex-1 space-y-6 p-4 md:p-8 pt-6 relative">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
            <h2 className="text-3xl font-bold tracking-tight">{t.title}</h2>
            <p className="text-muted-foreground text-sm mt-1">{t.subtitle}</p>
          </div>
          <div className="flex flex-col sm:flex-row items-center gap-2">
            <span className="text-sm font-medium text-muted-foreground">{lang === 'es' ? 'Ordenar por:' : 'Sort by:'}</span>
            <select 
              value={`${sortConfig.key}-${sortConfig.direction}`}
              onChange={(e) => {
                const [key, direction] = e.target.value.split('-')
                setSortConfig({ key, direction })
              }}
              className="h-9 px-3 py-1 bg-background border border-border rounded-md text-sm outline-none focus:ring-2 focus:ring-primary/50"
            >
              <option value="created_at-desc">{lang === 'es' ? 'Más recientes' : 'Newest'}</option>
              <option value="created_at-asc">{lang === 'es' ? 'Más antiguos' : 'Oldest'}</option>
              <option value="client_name-asc">{lang === 'es' ? 'Cliente (A-Z)' : 'Client (A-Z)'}</option>
              <option value="client_name-desc">{lang === 'es' ? 'Cliente (Z-A)' : 'Client (Z-A)'}</option>
              <option value="quoted_premium-desc">{lang === 'es' ? 'Prima Cotizada (Mayor a Menor)' : 'Premium (High to Low)'}</option>
              <option value="quoted_premium-asc">{lang === 'es' ? 'Prima Cotizada (Menor a Mayor)' : 'Premium (Low to High)'}</option>
              <option value="status-asc">{lang === 'es' ? 'Estatus' : 'Status'}</option>
            </select>
          </div>
        </div>

      <div className="rounded-xl border bg-card text-card-foreground shadow-sm overflow-hidden">
        {loading ? (
          <div className="p-8 text-center text-muted-foreground">{t.loading}</div>
        ) : proposals.length === 0 ? (
          <div className="p-8 text-center text-muted-foreground">{t.empty}</div>
        ) : (
          <>
            {/* Mobile View */}
            <div className="grid grid-cols-1 gap-4 p-4 md:hidden">
              {paginatedProposals.map((quote) => (
                <div key={quote.id} className="border border-border/50 rounded-xl p-5 space-y-4 bg-gradient-to-b from-muted/10 to-transparent shadow-sm relative overflow-hidden">
                  
                  <div className={`absolute top-0 left-0 w-1 h-full ${
                    quote.status === 'ACCEPTED' ? 'bg-emerald-500' :
                    quote.status === 'REJECTED' ? 'bg-red-500' :
                    'bg-blue-500'
                  }`} />

                  <div className="flex justify-between items-start pl-2">
                    <div>
                      <select 
                        value={quote.status}
                        onChange={(e) => handleStatusChange(quote.id, e.target.value)}
                        className={`mb-2 px-2.5 py-1 rounded-full text-[10px] font-bold tracking-wider uppercase border outline-none appearance-none cursor-pointer ${
                          quote.status === 'ACCEPTED' ? 'bg-emerald-500/10 text-emerald-600 border-emerald-500/30' :
                          quote.status === 'REJECTED' ? 'bg-red-500/10 text-red-600 border-red-500/30' :
                          quote.status === 'PROCESSING' ? 'bg-amber-500/10 text-amber-600 border-amber-500/30' :
                          'bg-blue-500/10 text-blue-600 border-blue-500/30'
                        }`}
                      >
                          <option value="QUOTED">{t.statuses.QUOTED}</option>
                          <option value="PROCESSING">{t.statuses.PROCESSING}</option>
                          <option value="ACCEPTED">{t.statuses.ACCEPTED}</option>
                          <option value="REJECTED">{t.statuses.REJECTED}</option>
                      </select>
                      <h4 className="font-bold text-lg leading-tight text-foreground">{quote.client_name}</h4>
                      <p className="text-xs text-muted-foreground mt-1">{quote.client_business_type}</p>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-3 pl-2">
                    <div className="space-y-1">
                      <div className="text-[10px] uppercase font-semibold text-muted-foreground tracking-wider">{t.lineOfBusiness}</div>
                      <div className="text-sm font-medium text-foreground">{quote.coverage_requested}</div>
                    </div>
                    <div className="space-y-1">
                      <div className="text-[10px] uppercase font-semibold text-muted-foreground tracking-wider">{t.estimatedPremium}</div>
                      <div className="text-sm font-bold text-emerald-600">
                        ${quote.premium_amount ? quote.premium_amount.toLocaleString('en-US', {minimumFractionDigits: 2}) : '0.00'}
                      </div>
                    </div>
                  </div>

                  <div className="pt-2 pl-2 flex gap-2">
                    {(userProfile?.role === 'ADMIN' || userProfile?.role === 'DEMO') && (
                      <button 
                        onClick={() => setLogsQuote(quote)}
                        title="Ver registro de actividad"
                        className="bg-secondary text-secondary-foreground hover:bg-secondary/80 px-4 py-3 rounded-lg transition-colors flex items-center justify-center shadow-sm"
                      >
                        <History className="w-5 h-5" />
                      </button>
                    )}
                    <Link 
                        href={`/proposals/${quote.id}`}
                        className="flex-1 text-center bg-primary text-primary-foreground hover:bg-primary/90 px-4 py-3 rounded-lg text-sm font-semibold transition-colors flex items-center justify-center shadow-sm"
                    >
                      <Eye className="w-4 h-4 mr-2" />
                      {t.viewPresentation}
                    </Link>
                  </div>
                </div>
              ))}
            </div>

            {/* Desktop View */}
            <div className="hidden md:block overflow-x-auto">
              <table className="w-full text-sm text-left">
                <thead className="bg-muted/50 text-muted-foreground border-b border-border">
                  <tr>
                    <th className="px-6 py-3 font-medium">{t.client}</th>
                    <th className="px-6 py-3 font-medium">{t.business}</th>
                    <th className="px-6 py-3 font-medium">{t.coverages}</th>
                    <th className="px-6 py-3 font-medium">{t.totalPremium}</th>
                    <th className="px-6 py-3 font-medium">{t.status}</th>
                    <th className="px-6 py-3 font-medium text-right">{t.action}</th>
                  </tr>
                </thead>
                <tbody>
                  {paginatedProposals.map((quote) => (
                    <tr key={quote.id} className="border-b border-border last:border-0 hover:bg-muted/20 transition-colors">
                      <td className="px-6 py-4 font-bold">{quote.client_name}</td>
                      <td className="px-6 py-4 text-muted-foreground">{quote.client_business_type}</td>
                      <td className="px-6 py-4">{quote.coverage_requested}</td>
                      <td className="px-6 py-4 font-bold text-emerald-600">
                        ${quote.premium_amount ? quote.premium_amount.toLocaleString('en-US', {minimumFractionDigits: 2}) : '0.00'}
                      </td>
                      <td className="px-6 py-4">
                        <div className="relative inline-block">
                          <select 
                            value={quote.status}
                            onChange={(e) => handleStatusChange(quote.id, e.target.value)}
                            className={`text-xs font-semibold px-2 py-1.5 rounded-md border outline-none appearance-none cursor-pointer pr-6 ${
                              quote.status === 'ACCEPTED' ? 'bg-emerald-500/10 text-emerald-600 border-emerald-500/30' :
                              quote.status === 'REJECTED' ? 'bg-red-500/10 text-red-600 border-red-500/30' :
                              quote.status === 'PROCESSING' ? 'bg-amber-500/10 text-amber-600 border-amber-500/30' :
                              'bg-blue-500/10 text-blue-600 border-blue-500/30'
                            }`}
                          >
                            <option value="QUOTED">{t.statuses.QUOTED}</option>
                            <option value="PROCESSING">{t.statuses.PROCESSING}</option>
                            <option value="ACCEPTED">{t.statuses.ACCEPTED}</option>
                            <option value="REJECTED">{t.statuses.REJECTED}</option>
                          </select>
                          <div className="absolute inset-y-0 right-0 flex items-center px-1.5 pointer-events-none text-current opacity-70">
                            <svg className="w-3 h-3 fill-current" viewBox="0 0 20 20"><path d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" fillRule="evenodd"></path></svg>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4 text-right flex justify-end space-x-2">
                        {(userProfile?.role === 'ADMIN' || userProfile?.role === 'DEMO') && (
                          <button 
                            onClick={() => setLogsQuote(quote)}
                            title="Ver registro de actividad"
                            className="bg-secondary text-secondary-foreground hover:bg-secondary/80 px-3 py-2 rounded-md transition-colors inline-flex items-center"
                          >
                            <History className="w-4 h-4" />
                          </button>
                        )}
                        <Link 
                            href={`/proposals/${quote.id}`}
                            className="bg-primary text-primary-foreground hover:bg-primary/90 px-4 py-2 rounded-md text-sm font-medium transition-colors inline-flex items-center"
                        >
                            <Eye className="w-4 h-4 mr-2" />
                            {t.viewPresentation}
                        </Link>
                      </td>
                    </tr>
                  ))}
                </tbody>
                </table>
              </div>
              <div className="p-4 border-t border-border flex flex-col sm:flex-row items-center justify-between gap-4 bg-muted/5">
                <div className="flex items-center gap-2">
                  <span className="text-sm text-muted-foreground">{lang === 'es' ? 'Mostrar' : 'Show'}</span>
                  <select
                    value={itemsPerPage}
                    onChange={(e) => {
                      setItemsPerPage(Number(e.target.value))
                      setCurrentPage(1)
                    }}
                    className="h-8 px-2 bg-background border border-border rounded-md text-sm outline-none"
                  >
                    <option value={10}>10</option>
                    <option value={25}>25</option>
                    <option value={50}>50</option>
                    <option value={100}>100</option>
                  </select>
                  <span className="text-sm text-muted-foreground">{lang === 'es' ? 'por página' : 'per page'}</span>
                </div>
                
                <div className="flex items-center gap-2">
                  <button 
                    onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                    disabled={currentPage === 1}
                    className="px-3 py-1 rounded-md border border-border bg-background text-sm hover:bg-muted disabled:opacity-50 transition-colors"
                  >
                    {lang === 'es' ? 'Anterior' : 'Previous'}
                  </button>
                  <span className="text-sm font-medium min-w-[3rem] text-center">
                    {currentPage} / {totalPages || 1}
                  </span>
                  <button 
                    onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                    disabled={currentPage === totalPages || totalPages === 0}
                    className="px-3 py-1 rounded-md border border-border bg-background text-sm hover:bg-muted disabled:opacity-50 transition-colors"
                  >
                    {lang === 'es' ? 'Siguiente' : 'Next'}
                  </button>
                </div>
              </div>
            </>
        )}
      </div>

      <ActivityLogsModal
        isOpen={!!logsQuote}
        onClose={() => setLogsQuote(null)}
        entityType="quote_requests"
        entityId={logsQuote?.id}
        entityName={`${logsQuote?.client_name} - ${logsQuote?.coverage_requested}`}
      />
    </div>
  )
}
