const fs = require('fs');

const path = 'web/src/app/quotes/page.tsx';
let code = fs.readFileSync(path, 'utf8');

const tCode = `
  const t = {
    es: {
      successAssigned: "Solicitud reasignada",
      errorAssigned: "Error al asignar",
      addProposal: "Agrega al menos una propuesta",
      completeCarrier: "Completa Aseguradora y % de comisión para todas las propuestas",
      selectPayment: "Debes seleccionar al menos una opción de pago (Anual o Mensual) para productos principales",
      enterTotalPremium: "Ingresa la Prima Total para la opción de Pago Anual",
      enterMonthlyPayment: "Ingresa el Pago Mensual para la opción de Pago Mensual",
      uploadErrorPDF: "Error al subir el archivo PDF: ",
      successProcessed: "Cotización procesada exitosamente",
      dbError: "Error al guardar en base de datos",
      processError: "Ocurrió un error al procesar",
      statusError: "Error al actualizar estatus",
      uploadingDoc: "Subiendo documento...",
      docSuccess: "Documento subido correctamente",
      docError: "Error al subir documento",
      inbox: "Bandeja de Solicitudes",
      all: "Todas",
      assignedToMe: "Asignadas a mí",
      createdByMe: "Creadas por mí",
      newQuote: "Nueva Cotización",
      loadingQuotes: "Cargando solicitudes...",
      noQuotes: "No hay solicitudes para mostrar.",
      statusMap: {
        PENDING_MANAGER: "Pendiente Manager",
        PENDING_AGENT: "Pendiente Agente",
        SUBMITTED_TO_CARRIER: "Enviada a Carrier",
        QUOTED: "Cotizado",
        REJECTED: "Rechazada",
        ACCEPTED: "Aceptada"
      },
      creator: "CREADOR",
      assignee: "ASIGNADO A",
      unassigned: "Sin asignar",
      carrier: "Aseguradora",
      coverage: "Cobertura",
      detailsTitle: "Detalles de la Solicitud",
      reassignTitle: "Reasignar",
      viewProposals: "Ver Propuestas",
      editQuote: "Editar Cotización",
      quote: "Cotizar",
      client: "Cliente",
      status: "Estado",
      action: "Acción",
      downloadPDF: "Descargar (PDF)",
      createdBy: "Creado Por",
      submittedForm: "Formulario Entregado",
      quoteProposals: "Propuestas de Cotización",
      commission: "Comisión",
      download: "Descargar",
      supportDocs: "Documentos de Respaldo",
      uploading: "Subiendo...",
      uploadDoc: "+ Subir Documento",
      noDocs: "No hay documentos de respaldo adjuntos a esta solicitud.",
      viewFile: "Ver Archivo",
      acceptQuote: "Aceptar Cotización",
      acceptQuoteDesc: "Ingresa la información final para cerrar esta solicitud.",
      soldPremium: "Prima Vendida ($)",
      commissionPercentage: "% de Comisión",
      commissionInternal: "% Comisión (Interno)",
      cancel: "Cancelar",
      saving: "Guardando...",
      reassignDesc: "Asigna esta cotización a otro miembro de tu agencia.",
      member: "Miembro",
      select: "Seleccionar...",
      assign: "Asignar",
      sendQuotes: "Enviar Cotizaciones",
      productCoverage: "Producto / Cobertura",
      selectCarrier: "Seleccionar Aseguradora...",
      bundleQuote: "Cotización en Conjunto (Bundle)",
      bundleDesc: "Agrupa el precio de este producto con el paquete principal",
      paymentOptions: "Opciones de Pago",
      annualPayment: "Pago Anual",
      monthlyPayment: "Pago Mensual",
      totalPremium: "Prima Total ($)",
      downpayment: "Enganche ($)",
      includedInBundle: "El precio de este producto está incluido en el paquete principal.",
      coveragesLimits: "Coberturas / Límites (Separadas por el símbolo |)",
      includes: "Qué INCLUYE (Separado por |)",
      excludes: "Qué EXCLUYE (Separado por |)",
      uwNotes: "Notas de Underwriting / Condiciones",
      quotePDF: "PDF de Cotización (Opcional - Interno)",
      addAnotherProposal: "Agregar otra propuesta",
      savingUploading: "Guardando y Subiendo...",
      sendToAgent: "Enviar a Agente",
      generatingPDF: "Generando PDF premium...",
      pdfSuccess: "PDF descargado exitosamente",
      pdfError: "Error al generar el PDF"
    },
    en: {
      successAssigned: "Request reassigned",
      errorAssigned: "Error assigning",
      addProposal: "Add at least one proposal",
      completeCarrier: "Complete Carrier and Commission % for all proposals",
      selectPayment: "You must select at least one payment option (Annual or Monthly) for main products",
      enterTotalPremium: "Enter the Total Premium for Annual Payment option",
      enterMonthlyPayment: "Enter the Monthly Payment for Monthly Payment option",
      uploadErrorPDF: "Error uploading PDF file: ",
      successProcessed: "Quote processed successfully",
      dbError: "Error saving to database",
      processError: "An error occurred while processing",
      statusError: "Error updating status",
      uploadingDoc: "Uploading document...",
      docSuccess: "Document uploaded successfully",
      docError: "Error uploading document",
      inbox: "Requests Inbox",
      all: "All",
      assignedToMe: "Assigned to me",
      createdByMe: "Created by me",
      newQuote: "New Quote",
      loadingQuotes: "Loading requests...",
      noQuotes: "No requests to display.",
      statusMap: {
        PENDING_MANAGER: "Pending Manager",
        PENDING_AGENT: "Pending Agent",
        SUBMITTED_TO_CARRIER: "Submitted to Carrier",
        QUOTED: "Quoted",
        REJECTED: "Rejected",
        ACCEPTED: "Accepted"
      },
      creator: "CREATOR",
      assignee: "ASSIGNED TO",
      unassigned: "Unassigned",
      carrier: "Carrier",
      coverage: "Coverage",
      detailsTitle: "Request Details",
      reassignTitle: "Reassign",
      viewProposals: "View Proposals",
      editQuote: "Edit Quote",
      quote: "Quote",
      client: "Client",
      status: "Status",
      action: "Action",
      downloadPDF: "Download (PDF)",
      createdBy: "Created By",
      submittedForm: "Submitted Form",
      quoteProposals: "Quote Proposals",
      commission: "Commission",
      download: "Download",
      supportDocs: "Supporting Documents",
      uploading: "Uploading...",
      uploadDoc: "+ Upload Document",
      noDocs: "No supporting documents attached to this request.",
      viewFile: "View File",
      acceptQuote: "Accept Quote",
      acceptQuoteDesc: "Enter final information to close this request.",
      soldPremium: "Sold Premium ($)",
      commissionPercentage: "Commission %",
      commissionInternal: "Commission % (Internal)",
      cancel: "Cancel",
      saving: "Saving...",
      reassignDesc: "Assign this quote to another member of your agency.",
      member: "Member",
      select: "Select...",
      assign: "Assign",
      sendQuotes: "Send Quotes",
      productCoverage: "Product / Coverage",
      selectCarrier: "Select Carrier...",
      bundleQuote: "Bundle Quote",
      bundleDesc: "Groups the price of this product with the main package",
      paymentOptions: "Payment Options",
      annualPayment: "Annual Payment",
      monthlyPayment: "Monthly Payment",
      totalPremium: "Total Premium ($)",
      downpayment: "Downpayment ($)",
      includedInBundle: "The price of this product is included in the main package.",
      coveragesLimits: "Coverages / Limits (Separated by |)",
      includes: "What's INCLUDED (Separated by |)",
      excludes: "What's EXCLUDED (Separated by |)",
      uwNotes: "Underwriting Notes / Conditions",
      quotePDF: "Quote PDF (Optional - Internal)",
      addAnotherProposal: "Add another proposal",
      savingUploading: "Saving and Uploading...",
      sendToAgent: "Send to Agent",
      generatingPDF: "Generating premium PDF...",
      pdfSuccess: "PDF downloaded successfully",
      pdfError: "Error generating PDF"
    }
  }[lang]
`;

// Insert the dictionary after useLanguage hook
code = code.replace(/const lang = useLanguage\(\)/, `const lang = useLanguage()\n${tCode}`);

const replacements = [
  // Toasts
  { target: '"Solicitud reasignada"', replacement: 't.successAssigned' },
  { target: '"Error al asignar"', replacement: 't.errorAssigned' },
  { target: '"Agrega al menos una propuesta"', replacement: 't.addProposal' },
  { target: '"Completa Aseguradora y % de comisión para todas las propuestas"', replacement: 't.completeCarrier' },
  { target: '"Debes seleccionar al menos una opción de pago (Anual o Mensual) para productos principales"', replacement: 't.selectPayment' },
  { target: '"Ingresa la Prima Total para la opción de Pago Anual"', replacement: 't.enterTotalPremium' },
  { target: '"Ingresa el Pago Mensual para la opción de Pago Mensual"', replacement: 't.enterMonthlyPayment' },
  { target: '"Error al subir el archivo PDF: "', replacement: 't.uploadErrorPDF' },
  { target: '"Cotización procesada exitosamente"', replacement: 't.successProcessed' },
  { target: '"Error al guardar en base de datos"', replacement: 't.dbError' },
  { target: '"Ocurrió un error al procesar"', replacement: 't.processError' },
  { target: '"Error al actualizar estatus"', replacement: 't.statusError' },
  { target: '"Subiendo documento..."', replacement: 't.uploadingDoc' },
  { target: '"Documento subido correctamente"', replacement: 't.docSuccess' },
  { target: '"Error al subir documento"', replacement: 't.docError' },
  { target: '"Generando PDF premium..."', replacement: 't.generatingPDF' },
  { target: '"PDF descargado exitosamente"', replacement: 't.pdfSuccess' },
  { target: '"Error al generar el PDF"', replacement: 't.pdfError' },

  // View UI Strings
  { target: "lang === 'es' ? 'Bandeja de Solicitudes' : 'Requests Inbox'", replacement: "t.inbox" },
  { target: "lang === 'es' ? 'Todas' : 'All'", replacement: "t.all" },
  { target: "lang === 'es' ? 'Asignadas a mí' : 'Assigned to me'", replacement: "t.assignedToMe" },
  { target: "lang === 'es' ? 'Creadas por mí' : 'Created by me'", replacement: "t.createdByMe" },
  { target: "lang === 'es' ? 'Nueva Cotización' : 'New Quote'", replacement: "t.newQuote" },
  { target: "Cargando solicitudes...", replacement: "{t.loadingQuotes}" },
  { target: "No hay solicitudes para mostrar.", replacement: "{t.noQuotes}" },
  
  // Status Maps (Mobile & Desktop)
  { target: '>Pendiente Manager<', replacement: '>{t.statusMap.PENDING_MANAGER}<', all: true },
  { target: '>Pendiente Agente<', replacement: '>{t.statusMap.PENDING_AGENT}<', all: true },
  { target: '>Enviada a Carrier<', replacement: '>{t.statusMap.SUBMITTED_TO_CARRIER}<', all: true },
  { target: '>Cotizado<', replacement: '>{t.statusMap.QUOTED}<', all: true },
  { target: '>Rechazada<', replacement: '>{t.statusMap.REJECTED}<', all: true },
  { target: '>Aceptada<', replacement: '>{t.statusMap.ACCEPTED}<', all: true },

  { target: 'Aseguradora<', replacement: '{t.carrier}<', all: true },
  { target: 'Cobertura<', replacement: '{t.coverage}<', all: true },
  { target: '>CREADOR<', replacement: '>{t.creator}<', all: true },
  { target: '>ASIGNADO A<', replacement: '>{t.assignee}<', all: true },
  { target: "'Sin asignar'", replacement: "t.unassigned", all: true },
  { target: 'title="Ver Detalles"', replacement: 'title={t.detailsTitle}', all: true },
  { target: 'title="Reasignar"', replacement: 'title={t.reassignTitle}', all: true },
  { target: '>Ver Propuestas<', replacement: '>{t.viewProposals}<', all: true },
  { target: 'title="Editar Cotización"', replacement: 'title={t.editQuote}', all: true },
  { target: '>Cotizar<', replacement: '>{t.quote}<', all: true },
  { target: '>Cliente<', replacement: '>{t.client}<', all: true },
  { target: '>Estado<', replacement: '>{t.status}<', all: true },
  { target: '>Acción<', replacement: '>{t.action}<', all: true },
  { target: '>Detalles de la Solicitud<', replacement: '>{t.detailsTitle}<', all: true },
  { target: 'Descargar (PDF)', replacement: '{t.downloadPDF}', all: true },
  { target: 'Creado Por', replacement: '{t.createdBy}', all: true },
  { target: '>Formulario Entregado<', replacement: '>{t.submittedForm}<', all: true },
  { target: '>Propuestas de Cotización<', replacement: '>{t.quoteProposals}<', all: true },
  { target: 'Comisión: ', replacement: '{t.commission}: ' },
  { target: '>Descargar<', replacement: '>{t.download}<', all: true },
  { target: '>Documentos de Respaldo<', replacement: '>{t.supportDocs}<', all: true },
  { target: "isUploadingDoc ? 'Subiendo...' : '+ Subir Documento'", replacement: "isUploadingDoc ? t.uploading : t.uploadDoc" },
  { target: 'No hay documentos de respaldo adjuntos a esta solicitud.', replacement: '{t.noDocs}' },
  { target: 'Ver Archivo', replacement: '{t.viewFile}', all: true },
  { target: '>Aceptar Cotización<', replacement: '>{t.acceptQuote}<', all: true },
  { target: '>Ingresa la información final para cerrar esta solicitud.<', replacement: '>{t.acceptQuoteDesc}<', all: true },
  { target: 'Prima Vendida ($)', replacement: '{t.soldPremium}', all: true },
  { target: '% de Comisión', replacement: '{t.commissionPercentage}', all: true },
  { target: '>Cancelar<', replacement: '>{t.cancel}<', all: true },
  { target: 'isUploading ? "Guardando..." : "Aceptar Cotización"', replacement: 'isUploading ? t.saving : t.acceptQuote' },
  { target: '>Reasignar Solicitud<', replacement: '>{t.reassignTitle}<', all: true },
  { target: '>Asigna esta cotización a otro miembro de tu agencia.<', replacement: '>{t.reassignDesc}<', all: true },
  { target: '>Miembro<', replacement: '>{t.member}<', all: true },
  { target: '>Seleccionar...<', replacement: '>{t.select}<', all: true },
  { target: 'isUploading ? "Guardando..." : "Asignar"', replacement: 'isUploading ? t.saving : t.assign' },
  { target: '>Enviar Cotizaciones<', replacement: '>{t.sendQuotes}<', all: true },
  { target: 'Producto / Cobertura', replacement: '{t.productCoverage}' },
  { target: 'Seleccionar Aseguradora...', replacement: '{t.selectCarrier}', all: true },
  { target: 'Cotización en Conjunto (Bundle)', replacement: '{t.bundleQuote}', all: true },
  { target: 'Agrupa el precio de este producto con el paquete principal', replacement: '{t.bundleDesc}', all: true },
  { target: 'Opciones de Pago', replacement: '{t.paymentOptions}', all: true },
  { target: 'Pago Anual', replacement: '{t.annualPayment}', all: true },
  { target: 'Pago Mensual', replacement: '{t.monthlyPayment}', all: true },
  { target: 'Prima Total ($)', replacement: '{t.totalPremium}', all: true },
  { target: 'Enganche ($)', replacement: '{t.downpayment}', all: true },
  { target: 'El precio de este producto está incluido en el paquete principal.', replacement: '{t.includedInBundle}', all: true },
  { target: '% Comisión (Interno)', replacement: '{t.commissionInternal}', all: true },
  { target: 'Coberturas / Límites (Separadas por el símbolo |)', replacement: '{t.coveragesLimits}', all: true },
  { target: 'Qué INCLUYE (Separado por |)', replacement: '{t.includes}', all: true },
  { target: 'Qué EXCLUYE (Separado por |)', replacement: '{t.excludes}', all: true },
  { target: 'Notas de Underwriting / Condiciones', replacement: '{t.uwNotes}', all: true },
  { target: 'PDF de Cotización (Opcional - Interno)', replacement: '{t.quotePDF}', all: true },
  { target: 'Agregar otra propuesta', replacement: '{t.addAnotherProposal}', all: true },
  { target: 'isUploading ? "Guardando y Subiendo..." : (', replacement: 'isUploading ? t.savingUploading : (' },
  { target: 'Enviar a Agente', replacement: '{t.sendToAgent}', all: true },
  { target: 'Ver Documento', replacement: '{t.viewFile}', all: true }
];

replacements.forEach(r => {
  if (r.all) {
    code = code.split(r.target).join(r.replacement);
  } else {
    code = code.replace(r.target, r.replacement);
  }
});

// Write it back
fs.writeFileSync(path, code);
